### ISSUE TITLE
Document spec build process

### ISSUE THREAD

**Issue by kba** [kba/hocr-spec#30]

**Comment by kba** [comment]
Adressed in https://github.com/kba/hocr-spec/commit/82272dc5dcdc97595445326d5b8a4e85c1060a9b

**Comment by amitdo** [comment]
I followed the instructions, and was able to build the spec after editing `spec.md`.

**Comment by zuphilip** [comment]
I had some problems installing bikeshed in my ubuntu docker (after the installation the command `bikeshed` was still unknown...). In the end I used the online service https://api.csswg.org/bikeshed/, which we could also use as an alternative:

```
$ curl https://api.csswg.org/bikeshed/ -F file=@index.bs  > index.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  192k    0  150k  100 42082  24493   6666  0:00:06  0:00:06 --:--:-- 32445
```

**Comment by kba** [comment]
You mean the Makefile output `bikeshed and docker not installed` and returned 1? That is weird, can you run `docker run --rm -it -v $PWD:/data kbai/bikeshed spec 1.2/index.bs` in a shell?

Yes,  we could add the web API as a third option to native python and docker.

**Comment by amitdo** [comment]
Did you install bikeshed with or without 'sudo'?

I installed it in a regular Ubuntu (not docker) without 'sudo'. In that case, you need to add '~/.local/bin' to the PATH environment variable.

**Comment by zuphilip** [comment]
@kba Yes, that works!

@amitdo This might be the problem, I can maybe try next time but now the docker container is deleted again (I have to look for my space a little...)

**Comment by wanghaisheng** [comment]
@kba 

```
➜  hocr-spec git:(zh-1.2) ✗ make VERSION=1.2-zh
/bin/sh: line 0: return: can only `return' from a function or sourced script
/bin/sh: line 0: return: can only `return' from a function or sourced script
/bin/sh: line 0: return: can only `return' from a function or sourced script
/bin/sh: line 0: return: can only `return' from a function or sourced script
case "docker curl" in \
        bikeshed) bikeshed -f spec 1.2-zh/index.bs ;; \
        docker) docker run --rm -it -v /Users/wanghaisheng/workspace/hocr-spec:/data kbai/bikeshed -f spec 1.2-zh/index.bs ;; \
        curl) curl "https://api.csswg.org/bikeshed/" -o 1.2-zh/index.html -F file=@1.2-zh/index.bs ;; \
        *) echo 'Unsupported bikeshed backend "docker curl"'; exit 1 ;;\
    esac
Unsupported bikeshed backend "docker curl"
make: *** [1.2-zh/index.html] Error 1
➜  hocr-spec git:(zh-1.2) ✗ docker run --rm -it -v /Users/wanghaisheng/workspace/hocr-spec:/data kbai/bikeshed -f spec 1.2-zh/index.bs
Unable to find image 'kbai/bikeshed:latest' locally
^C
➜  hocr-spec git:(zh-1.2) ✗ $(shell for cmd in bikeshed docker curl;do type >/dev/null 2>&1 $$cmd && echo $$cmd && return;done)

zsh: parse error near `do'
zsh: parse error near `$(shell for cmd in b...'
```

**Comment by kba** [comment]
@wanghaisheng  6187f6e should fix it.
