### ISSUE TITLE
Flags are not rendered

### ISSUE THREAD

**Issue by zuphilip** [kba/hocr-spec#31]
It seems that if you use the flags `:gb:` or `:cn:` within link context, then they are not rendered as expected.

**Comment by kba** [comment]
Looks fine for me?

![image](https://cloud.githubusercontent.com/assets/273367/18970574/08abbae0-8692-11e6-9ee8-581e5981ea82.png)

**Comment by zuphilip** [comment]
Not for me :-(

![screenshot - sep 29 2016 10 36 pm](https://cloud.githubusercontent.com/assets/5199995/18971431/53322d94-8695-11e6-9345-c5331504d2a0.png)

**Comment by zuphilip** [comment]
Hm.. that is strange. I tried https://www.browserling.com/ and it looks fine there as well. Thus, it is maybe really just me...

**Comment by amitdo** [comment]
Which browser?

I see the flags in Firefox.

**Comment by zuphilip** [comment]
Yeah, actually I don't see flags in Firefox nor Chrome on my Win 8 machine. It seems that it is just me, thus we can close the issue here and I have to figure this our myself...

**Comment by amitdo** [comment]
Related:
[Do not use flag icons to indicate languages](https://www.google.co.il/search?q=Do+not+use+flag+icons+to+indicate+languages)

**Comment by kba** [comment]
Yeah, totally with you, I [don't think it's a great idea to equate country and language](https://github.com/kba/hocr-spec/pull/29#issuecomment-250448903), it's just convenient. Let's change that, what do you propose? Link the version number to the normative English spec and add the link to the translation as text in braces?

@wanghaisheng What term would you prefer to describe the language of your translation? Chinese? Chinese (simplified)? Chinese (Mainland China)?

**Comment by kba** [comment]
Bikeshed links zh_CN as 简体中文 with tooltip "Simplified Chinese".

**Comment by amitdo** [comment]
[English][中文 – Chinese]

**Comment by amitdo** [comment]
Wikipedia calls Simplified Chinese 'Chinese'.

**Comment by kba** [comment]
Point taken, Chinese it is.

**Comment by amitdo** [comment]
@zuphilip's issue is now solved, no flags - for anyone, not just him :)

**Comment by amitdo** [comment]
'Flags are not rendered' - It's not a bug, it's (now) a feature! :)

**Comment by amitdo** [comment]
https://github.com/kba/hocr-spec
1.1 English, 中文 (Chinese)
https://kba.github.io/hocr-spec/1.2/
Translations (non-normative and likely out-of-date):
    简体中文 

Inconsistency...

Wikipedia uses 中文 for 'Chinese' in its 'Languages' section.

**Comment by kba** [comment]
Yeah, that's bikeshed's localized name for `zh_CN`, that's why I used that before. To change that, need to dig in bikeshed. Maybe open another issue for it, since it's low priority since the translation doesn't exist yet. Until then, I take out the link.
