### ISSUE TITLE
bbox x0 y0 x1 y1

### ISSUE THREAD

**Issue by wanghaisheng** [kba/hocr-spec#34]
where is the bbox x0 y0 x1 y1 detail description?
how to compute  x0 y0 x1 y1 ? 
whether it a relative value or not

**Comment by kba** [comment]
Related: https://github.com/tmbdev/ocropy/issues/107

**Comment by kba** [comment]
A more in-depth description would indeed help, the two sections are not precise enough.

>  whether it a relative value or not

It's always an absolute value, i.e. relative to the the top-left corner of the original image and measured in pixels.

**Comment by amitdo** [comment]
In Tesseract's hOCR:

`bbox left top right bottom`

https://github.com/tesseract-ocr/tesseract/blob/57d28b2643/api/baseapi.cpp#L1402
https://github.com/tesseract-ocr/tesseract/blob/57d28b2643/api/baseapi.cpp#L1502

**Comment by zuphilip** [comment]
How about a picture illustrating the origin and one box with its values?

**Comment by zuphilip** [comment]
Here is my attempt to create a picture for explaining the coordinates in `bbox` with an example:

![bbox-crop](https://cloud.githubusercontent.com/assets/5199995/19212875/8d05265c-8d5c-11e6-98e4-c30430d81ff3.png)

What do you think?

I suggest also to clarify the explanation for bbox:

``` diff
### `bbox`

`bbox x0 y0 x1 y1`

- The bounding box of the element relative to the document image
+ A rectangular box describing the geometric position of the element in the document image given by the upper-left corner (x0, y0) and the lower-right corner (x1, y1)

+  * the values are with reference to the the top-left corner of the original image and measured in pixels
+  * the order of the values are "left top right bottom"
  * use `x_bboxes` below for character bounding boxes
  * do not use `bbox` unless the bounding box of the layout component is, in
    fact, rectangular
  * some non-rectangular layout components may have rectangular bounding boxes
    if the non-rectangularity is caused by floating elements around which text flows

See also the section [[#bbox-typesetting]].
```

**Comment by wanghaisheng** [comment]
cool

**Comment by amitdo** [comment]
Nice drawing!

I think the phrase "**b**ounding **box**" should still be used.

**Comment by amitdo** [comment]
My suggestion, based on yours:
`bbox` - short for "bounding box". The bbox is the coordinate system of a rectangular around an element in the document image. The upper-left corner is 'x0, y0' and the lower-right corner is 'x1, y1'.

**Comment by kba** [comment]
I think `bbox` and its values are much clearer now.
