### ISSUE TITLE
'Other superscripts and subscripts...'

### ISSUE THREAD

**Issue by amitdo** [kba/hocr-spec#38]
Superscript and Subscript

> **Other** superscripts and subscripts must be represented using the HTML <sup> and <sub> tags

'Other' seems to refer to superscripts and subscripts within 'ocr_chem' and 'ocr_math'. If that's the case, this section should come after 'ocr_math'.

**Comment by amitdo** [comment]
Superscript and Subscript

>**Other** superscripts and subscripts must be represented using the HTML \<sup> and \<sub> tags

'Other' seems to refer to superscripts and subscripts within 'ocr_chem' and 'ocr_math'. If that's the case, this section should come after 'ocr_math'.

**Comment by kba** [comment]
Agree, what about: https://github.com/kba/hocr-spec/commit/1f5b5a3e88cd99b0c08ccac0b4850be66efb8681
