### ISSUE TITLE
Rendering of internal links

### ISSUE THREAD

**Issue by zuphilip** [kba/hocr-spec#46]
Is it possible to render the internal links in the html without the paragraph signs and section numbers? I feel that the readability suffers from this, e.g.

![hocr-spec-links](https://cloud.githubusercontent.com/assets/5199995/19094609/3686f4e0-8a91-11e6-9cef-bb23c6955f72.png)

Would you agree?

**Comment by kba** [comment]
Yeah, it's not perfect right now. Linking to generic headlines isn't ideal anyway, but there's lots of options in bikeshed for linking, see https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md and https://github.com/tabatkins/bikeshed/blob/master/docs/markup.md, https://github.com/tabatkins/bikeshed/blob/master/docs/definitions-autolinks.md etc. Want to investigate further, maybe next week or so.

**Comment by kba** [comment]
This has changed a lot, a cheatsheet how we reference terms is in #53, bikeshed has [easier docs now](https://tabatkins.github.io/bikeshed/)
