### ISSUE TITLE
"or alternatively can be indicated as properties on elements"

### ISSUE THREAD

**Issue by kba** [kba/hocr-spec#75]
> Language and writing direction should be indicated using the HTML standard
> attributes `lang=` and `dir=`, or alternatively can be indicated as properties on
> elements.

Not clear what that last clause means. Title properties `dir` and `lang`?

I would delete it, one standard mechanism for dir/lang is better.

**Comment by zuphilip** [comment]
👍 This looks also more conform with what is written somewhere else:
- "all writing direction changes must be indicated with tags." http://kba.github.io/hocr-spec/1.2/#hyphenation
- "ocrp_dir:  Capable of generating dir= attributes" http://kba.github.io/hocr-spec/1.2/#capabilities
