### ISSUE TITLE
"in the following"

### ISSUE THREAD

**Issue by kba** [kba/hocr-spec#91]
https://github.com/kba/hocr-spec/pull/84#issuecomment-256763853:

> An hOCR element (**in the following: element**) is...

Is that proper English?

https://www.quora.com/What-is-a-more-modern-way-to-say-hereinafter-referred-to-as

**Comment by kba** [comment]
@amitdo My point here is to emphasize that when using "element" in the spec, we mean "an HTML element with a single class `ocr_....`.

**Comment by kba** [comment]
>  (in this spec simply refered to as an element)

How about this?

**Comment by amitdo** [comment]
> (in this spec simply refered to as an element)

:+1:
